### PR TITLE
Update Dependencies and Codebase for Dart SDK 3.3.3 Compatibility

### PR DESCRIPTION
**Pull request by zerefati**
This pull request includes several updates and improvements to ensure compatibility with Dart SDK 3.3.3 and to enhance code quality:

- **Update package versions and dependencies**: Adjusted the package versions and dependencies to align with Dart SDK 3.3.3.
- **Code cleanup in Record class**: Removed a redundant if condition to streamline logic.
- **Optimize imports**: Eliminated unused imports across the codebase.
- **String literal standardization**: Standardized string literals to use single quotes in profiler.dart for consistency.

### CODE REVIEW

**Comment by andy1xx8** [comment]
@zerefati 
 
 Thanks for your contribution. I will review and release a new version soon
 For years, I'm so surprised that this tiny package is used by others. Could please share the usecase you use this package for?

**Comment by zerefati** [comment]
Hi @andy1xx8,

As I am developing an online shopping app that aggregates items from various e-commerce websites. Your package has been incredibly helpful for extracting products from websites cart as cart items, which I then use to create orders in our app datastore.

**Comment by andy1xx8** [comment]
@zerefati  Im glad to hear that my package can help you .

**Comment by zerefati** [comment]
@andy1xx8 could you please publish the new version to pub.dev?

Thanks.

**Comment by andy1xx8** [comment]
@zerefati  yes
I will publish a new version tonight ( I'm not at home now)

**Comment by zerefati** [comment]
Hi @andy1xx8,

Any updates on publishing to pub.dev?

**Pull request merged**
